#!/usr/bin/env python3
"""Validate the machine-readable release metadata contract."""

from __future__ import annotations

import csv
from pathlib import Path

CATALOG = Path('data/metadata/layer_catalog.csv')
MANIFEST = Path('data/metadata/release_manifest.csv')
REPRO = Path('docs/reproducibility.md')

REQUIRED_CANONICAL = {
    'communal_master_2026',
    'censo_connectivity_2024',
    'censo_social_context_2024',
    'casen_national_2024',
    'casen_macrozone_2024',
    'subtel_longitudinal_access',
    'subtel_microdata_inventory',
    'subtel_segmented_access',
    'subtel_affordability',
    'subtel_sector_2026q1',
    'subtel_sector_longitudinal_2026m03',
    'subtel_oti_fixed_speed_2026m01',
    'subtel_mobile_network_2025m03',
    'subtel_fixed_redacceso_presence',
    'mineduc_aulas_establishments_2025',
    'mineduc_aulas_communal_2025',
    'ookla_national_2026q1',
    'ookla_communal_2026q1',
    'commune_geography',
}

EXPECTED_NONCANONICAL = {
    'subtel_fixed_redacceso_length_audit',
}

REQUIRED_MANIFEST_PATHS = {
    'README.md',
    'CITATION.cff',
    'index.html',
    'assets/dashboard.js',
    'data/communal_master/chile_digital_inclusion_communes_2026_integrated.csv',
    'data/metadata/public_release_validation.csv',
    'data/oti_2026/regional_fixed_speed_2026_01.csv',
    'docs/oti_fixed_speed_2026.md',
    'docs/reproducibility.md',
    'docs/communal_master_dictionary.md',
    'geo/chile_communes.geojson',
}


def read_csv(path: Path):
    with path.open(encoding='utf-8-sig', newline='') as fh:
        return list(csv.DictReader(fh))


def main() -> None:
    for path in [CATALOG, MANIFEST, REPRO]:
        if not path.exists():
            raise RuntimeError(f'Missing release metadata file: {path}')

    catalog = read_csv(CATALOG)
    ids = [r['layer_id'] for r in catalog]
    if len(ids) != len(set(ids)):
        raise RuntimeError('Duplicate layer_id in layer catalog')

    expected_ids = REQUIRED_CANONICAL | EXPECTED_NONCANONICAL
    actual_ids = set(ids)
    if actual_ids != expected_ids:
        raise RuntimeError(
            'Layer catalog contract changed. '
            f'Missing={sorted(expected_ids-actual_ids)} Extra={sorted(actual_ids-expected_ids)}'
        )

    canonical = {r['layer_id'] for r in catalog if r['canonical'] == 'yes'}
    if canonical != REQUIRED_CANONICAL:
        raise RuntimeError(
            'Canonical layer contract changed. '
            f'Missing={sorted(REQUIRED_CANONICAL-canonical)} Extra={sorted(canonical-REQUIRED_CANONICAL)}'
        )
    unavailable = [r['layer_id'] for r in catalog if r['canonical'] == 'yes' and r['exists'] != 'yes']
    if unavailable:
        raise RuntimeError(f'Canonical catalog layers unavailable: {unavailable}')

    master = next(r for r in catalog if r['layer_id'] == 'communal_master_2026')
    if int(master['rows']) != 346 or int(master['columns']) != 89:
        raise RuntimeError(f'Catalog master shape mismatch: rows={master["rows"]} cols={master["columns"]}')

    longitudinal = next(r for r in catalog if r['layer_id'] == 'subtel_sector_longitudinal_2026m03')
    if int(longitudinal['rows']) != 2010 or int(longitudinal['columns']) != 9:
        raise RuntimeError(
            'SUBTEL longitudinal sector layer shape mismatch: '
            f'rows={longitudinal["rows"]} cols={longitudinal["columns"]}'
        )

    oti = next(r for r in catalog if r['layer_id'] == 'subtel_oti_fixed_speed_2026m01')
    if int(oti['rows']) != 16:
        raise RuntimeError(f'OTI regional layer must contain 16 regions, found {oti["rows"]}')

    manifest = read_csv(MANIFEST)
    if len(manifest) < 180:
        raise RuntimeError(f'Release manifest unexpectedly small: {len(manifest)} files')
    paths = [r['path'] for r in manifest]
    if len(paths) != len(set(paths)):
        raise RuntimeError('Duplicate path in release manifest')
    path_set = set(paths)
    missing = REQUIRED_MANIFEST_PATHS - path_set
    if missing:
        raise RuntimeError(f'Manifest missing required public files: {sorted(missing)}')
    if 'data/metadata/release_manifest.csv' in path_set or 'data/metadata/layer_catalog.csv' in path_set:
        raise RuntimeError('Autogenerated release metadata must not hash itself')

    bad_hashes = [r['path'] for r in manifest if len(r.get('sha256', '')) != 64]
    if bad_hashes:
        raise RuntimeError(f'Invalid SHA-256 entries: {bad_hashes[:10]}')

    print('release_metadata PASS')
    print('layers', len(catalog), 'canonical', len(canonical), 'manifest_files', len(manifest))
    print('master_shape', master['rows'], 'x', master['columns'])
    print('sector_longitudinal_shape', longitudinal['rows'], 'x', longitudinal['columns'])
    print('oti_regions', oti['rows'])


if __name__ == '__main__':
    main()
